#先配置相关访问的servlet的端口号，项目名称
server:
port: 80
servlet:
context-path: /day120301


#数据源
spring:
datasource:
driver-class-name: com.mysql.cj.jdbc.Driver
url: jdbc:mysql:///test?characterEncoding=utf-8&serverTimezone=UTC
username: root
password: root
type: com.alibaba.druid.pool.DruidDataSource


#编写mybatis的配置信息
#扫描映射文件
mybatis:
mapper-locations: mapper/*.xml
configuration:
map-underscore-to-camel-case: true
type-aliases-package:  com.broit.day120301.entity
